name: Publish package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v4
      
      # https://stackoverflow.com/a/73639034
    - name: Get package.json content
      run: |
        echo "PACKAGE_JSON=$(jq -c . < package.json)" >>$GITHUB_ENV
    - name: Check version
      run: |
        [[ "${{github.ref_name}}" && "${{ fromJson(env.PACKAGE_JSON).version }}" == *"${{ github.ref_name }}"* ]]
    
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install vsce
      run: npm install -g '@vscode/vsce'
    - name: Login VSCE
      run: echo ${{ secrets.VSCE_PAT }} | vsce login ${{ secrets.VSCE_PUBLISHER }}
    - name: Verify publish access rights
      run: vsce verify-pat --pat ${{ secrets.VSCE_PAT }}
    - name: Publish package
      run: vsce publish

   
            

